<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Normalizer;

use Jane\JsonSchemaRuntime\Normalizer\CheckArray;
use Jane\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ObjectListPaginationNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use CheckArray;
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \OParl\Model\ObjectListPagination();
        if (\array_key_exists('totalElements', $data)) {
            $object->setTotalElements($data['totalElements']);
        }
        if (\array_key_exists('elementsPerPage', $data)) {
            $object->setElementsPerPage($data['elementsPerPage']);
        }
        if (\array_key_exists('currentPage', $data)) {
            $object->setCurrentPage($data['currentPage']);
        }
        if (\array_key_exists('totalPages', $data)) {
            $object->setTotalPages($data['totalPages']);
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getTotalElements()) {
            $data['totalElements'] = $object->getTotalElements();
        }
        if (null !== $object->getElementsPerPage()) {
            $data['elementsPerPage'] = $object->getElementsPerPage();
        }
        if (null !== $object->getCurrentPage()) {
            $data['currentPage'] = $object->getCurrentPage();
        }
        if (null !== $object->getTotalPages()) {
            $data['totalPages'] = $object->getTotalPages();
        }

        return $data;
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'OParl\\Model\\ObjectListPagination';
    }

    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof \OParl\Model\ObjectListPagination;
    }
}
