<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Model;

class ObjectListLinks
{
    /**
     * @var string
     */
    protected $first;
    /**
     * @var string
     */
    protected $prev;
    /**
     * @var string
     */
    protected $self;
    /**
     * @var string
     */
    protected $next;
    /**
     * @var string
     */
    protected $last;
    /**
     * @var string
     */
    protected $web;

    public function getFirst(): string
    {
        return $this->first;
    }

    public function setFirst(string $first): self
    {
        $this->first = $first;

        return $this;
    }

    public function getPrev(): string
    {
        return $this->prev;
    }

    public function setPrev(string $prev): self
    {
        $this->prev = $prev;

        return $this;
    }

    public function getSelf(): string
    {
        return $this->self;
    }

    public function setSelf(string $self): self
    {
        $this->self = $self;

        return $this;
    }

    public function getNext(): string
    {
        return $this->next;
    }

    public function setNext(string $next): self
    {
        $this->next = $next;

        return $this;
    }

    public function getLast(): string
    {
        return $this->last;
    }

    public function setLast(string $last): self
    {
        $this->last = $last;

        return $this;
    }

    public function getWeb(): string
    {
        return $this->web;
    }

    public function setWeb(string $web): self
    {
        $this->web = $web;

        return $this;
    }
}
