<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Model;

class ObjectList
{
    /**
     * @var ObjectListPagination
     */
    protected $pagination;
    /**
     * @var ObjectListLinks
     */
    protected $links;

    public function getPagination(): ObjectListPagination
    {
        return $this->pagination;
    }

    public function setPagination(ObjectListPagination $pagination): self
    {
        $this->pagination = $pagination;

        return $this;
    }

    public function getLinks(): ObjectListLinks
    {
        return $this->links;
    }

    public function setLinks(ObjectListLinks $links): self
    {
        $this->links = $links;

        return $this;
    }
}
