<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Model;

class Organization
{
    /**
     * @var string
     */
    protected $body;
    /**
     * @var string
     */
    protected $classification;
    /**
     * @var string
     */
    protected $consultation;
    /**
     * @var \DateTime
     */
    protected $created;
    /**
     * @var bool
     */
    protected $deleted = false;
    /**
     * @var \DateTime
     */
    protected $endDate;
    /**
     * @var string
     */
    protected $externalBody;
    /**
     * Every object *must* carry a URL as ID.
     *
     * @var string
     */
    protected $id;
    /**
     * @var string[]
     */
    protected $keyword;
    /**
     * @var string|null
     */
    protected $license;
    /**
     * @var Location
     */
    protected $location;
    /**
     * @var string
     */
    protected $meeting;
    /**
     * @var string[]
     */
    protected $membership;
    /**
     * @var \DateTime
     */
    protected $modified;
    /**
     * Every object *must* carry a name.
     *
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $organizationType;
    /**
     * @var string[]
     */
    protected $post;
    /**
     * @var string|null
     */
    protected $shortName;
    /**
     * @var \DateTime
     */
    protected $startDate;
    /**
     * @var string
     */
    protected $subOrganizationOf;
    /**
     * @var string
     */
    protected $type = 'https://schema.oparl.org/1.1/Organization';
    /**
     * @var string|null
     */
    protected $web;
    /**
     * @var string
     */
    protected $website;

    public function getBody(): string
    {
        return $this->body;
    }

    public function getClassification(): string
    {
        return $this->classification;
    }

    public function getConsultation(): string
    {
        return $this->consultation;
    }

    public function getCreated(): \DateTime
    {
        return $this->created;
    }

    public function getDeleted(): bool
    {
        return $this->deleted;
    }

    public function getEndDate(): \DateTime
    {
        return $this->endDate;
    }

    public function getExternalBody(): string
    {
        return $this->externalBody;
    }

    /**
     * Every object *must* carry a URL as ID.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @return string[]
     */
    public function getKeyword(): array
    {
        return $this->keyword;
    }

    public function getLicense(): ?string
    {
        return $this->license;
    }

    public function getLocation(): Location
    {
        return $this->location;
    }

    public function getMeeting(): string
    {
        return $this->meeting;
    }

    /**
     * @return string[]
     */
    public function getMembership(): array
    {
        return $this->membership;
    }

    public function getModified(): \DateTime
    {
        return $this->modified;
    }

    /**
     * Every object *must* carry a name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    public function getOrganizationType(): string
    {
        return $this->organizationType;
    }

    /**
     * @return string[]
     */
    public function getPost(): array
    {
        return $this->post;
    }

    public function getShortName(): ?string
    {
        return $this->shortName;
    }

    public function getStartDate(): \DateTime
    {
        return $this->startDate;
    }

    public function getSubOrganizationOf(): string
    {
        return $this->subOrganizationOf;
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function getWebsite(): string
    {
        return $this->website;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function setClassification(string $classification): self
    {
        $this->classification = $classification;

        return $this;
    }

    public function setConsultation(string $consultation): self
    {
        $this->consultation = $consultation;

        return $this;
    }

    public function setCreated(\DateTime $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function setEndDate(\DateTime $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function setExternalBody(string $externalBody): self
    {
        $this->externalBody = $externalBody;

        return $this;
    }

    /**
     * Every object *must* carry a URL as ID.
     */
    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param string[] $keyword
     */
    public function setKeyword(array $keyword): self
    {
        $this->keyword = $keyword;

        return $this;
    }

    public function setLicense(?string $license): self
    {
        $this->license = $license;

        return $this;
    }

    public function setLocation(Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function setMeeting(string $meeting): self
    {
        $this->meeting = $meeting;

        return $this;
    }

    /**
     * @param string[] $membership
     */
    public function setMembership(array $membership): self
    {
        $this->membership = $membership;

        return $this;
    }

    public function setModified(\DateTime $modified): self
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * Every object *must* carry a name.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function setOrganizationType(string $organizationType): self
    {
        $this->organizationType = $organizationType;

        return $this;
    }

    /**
     * @param string[] $post
     */
    public function setPost(array $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function setShortName(?string $shortName): self
    {
        $this->shortName = $shortName;

        return $this;
    }

    public function setStartDate(\DateTime $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function setSubOrganizationOf(string $subOrganizationOf): self
    {
        $this->subOrganizationOf = $subOrganizationOf;

        return $this;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }
}
