<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Model;

class OrganizationObjectList
{
    /**
     * @var Organization[]
     */
    protected $data;
    /**
     * @var ObjectListLinks
     */
    protected $links;
    /**
     * @var ObjectListPagination
     */
    protected $pagination;

    /**
     * @return Organization[]
     */
    public function getData(): array
    {
        return $this->data;
    }

    public function getLinks(): ObjectListLinks
    {
        return $this->links;
    }

    public function getPagination(): ObjectListPagination
    {
        return $this->pagination;
    }

    /**
     * @param Organization[] $data
     */
    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }

    public function setLinks(ObjectListLinks $links): self
    {
        $this->links = $links;

        return $this;
    }

    public function setPagination(ObjectListPagination $pagination): self
    {
        $this->pagination = $pagination;

        return $this;
    }
}
