<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace OParl\Model;

class System
{
    /**
     * @var string
     */
    protected $type = 'https://schema.oparl.org/1.1/System';
    /**
     * @var string
     */
    protected $oparlVersion = 'https://schema.oparl.org/1.1/';
    /**
     * @var string[]
     */
    protected $otherOparlVersions;
    /**
     * @var string
     */
    protected $body;
    /**
     * @var string
     */
    protected $contactEmail;
    /**
     * @var string
     */
    protected $contactName;
    /**
     * @var string
     */
    protected $website;
    /**
     * @var string
     */
    protected $vendor;
    /**
     * @var string
     */
    protected $product;

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getOparlVersion(): string
    {
        return $this->oparlVersion;
    }

    public function setOparlVersion(string $oparlVersion): self
    {
        $this->oparlVersion = $oparlVersion;

        return $this;
    }

    /**
     * @return string[]
     */
    public function getOtherOparlVersions(): array
    {
        return $this->otherOparlVersions;
    }

    /**
     * @param string[] $otherOparlVersions
     */
    public function setOtherOparlVersions(array $otherOparlVersions): self
    {
        $this->otherOparlVersions = $otherOparlVersions;

        return $this;
    }

    public function getBody(): string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getContactEmail(): string
    {
        return $this->contactEmail;
    }

    public function setContactEmail(string $contactEmail): self
    {
        $this->contactEmail = $contactEmail;

        return $this;
    }

    public function getContactName(): string
    {
        return $this->contactName;
    }

    public function setContactName(string $contactName): self
    {
        $this->contactName = $contactName;

        return $this;
    }

    public function getWebsite(): string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getVendor(): string
    {
        return $this->vendor;
    }

    public function setVendor(string $vendor): self
    {
        $this->vendor = $vendor;

        return $this;
    }

    public function getProduct(): string
    {
        return $this->product;
    }

    public function setProduct(string $product): self
    {
        $this->product = $product;

        return $this;
    }
}
